#!/bin/zsh

if (( !$+commands[antibody] )); then
    brew install antibody
fi

basedir=${0:a:h}
for file in ${basedir}/installs/**/.*
    ln -sfvn ${file} ~

# manually install antibody plugins
antibody bundle < ${basedir}/antibody/plugins > ~/.zplugins
