#!/usr/bin/ruby

def linkit(target, linkname)
    puts "linking #{target}"
    `ln -sfvn #{target} #{linkname}`
end

require 'fileutils'
include FileUtils

install_dir = Dir.pwd
user_home = File.expand_path('~')

cd(user_home)
puts pwd()

linkit("#{install_dir}/x/.Xdefaults", user_home)
linkit("#{install_dir}/vim/.vimrc", user_home)
Dir.glob("#{install_dir}/git/.git*") do |item|
    linkit(item, user_home)
end
Dir.glob("#{install_dir}/hg/.git*") do |item|
    linkit(item, user_home)
end

