[".zim/zimfw.zsh"]
  type = "file"
  url = "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
{{- if eq .osid "darwin" }}
[".config/alacritty/alacritty-themes"]
  type = "git-repo"
  url = "https://github.com/alacritty/alacritty-theme.git"
{{- end -}}
