[general]
import = [
  "~/.config/alacritty/alacritty-themes/themes/catppuccin_mocha.toml"
]

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font.normal]
family = "jetbrains mono"
