[general]
import = [
  "alacritty-theme/themes/catppuccini_frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 300, lines = 120 }
position = { x = 10, y = 10 }
padding = { x = 8, y = 8 }
dynamic_padding = true

[scrolling]
history = 100000

[font.normal]
family = "jetbrains mono"
